language: ruby
cache: bundler
sudo: false

before_install:
  - gem update --system
  # Update bundler to the latest
  - gem install bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - jruby-head
